### ISSUE TITLE
Unable to package android app with the latest version of ANE

### ISSUE THREAD

**Issue by subdan** [juank-pa/JKLocalNotifications-ANE#15]
When I create android package I get this error:
`aapt tool failed:ERROR: input directory '--auto-add-overlay' does not exists`

**Comment by subdan** [comment]
I noticed that only latest ANE doesn't work. ANE from October 15 works

**Comment by juank-pa** [comment]
@subdan I'm on it right now at PR #14.

**Comment by dr-mms** [comment]
I have the same issue

**Comment by juank-pa** [comment]
At first I had this problem too but then I added some options to the `android_options.xml` and fixed the issue. I found this on Stack Overflow. The weird thing is that I didn't have this issue before and the changes I made should not cause this. Another weird thing is that, after repairing the issue I tried to replicate the bug again using the old ANE files, but I just couldn't.

Anyway, I'm uploading the ANE today to PR #14. I'll keep you informed when that happens so you can try this ANE and give me your feedback on whether the issue was fixed or not.

**Comment by dr-mms** [comment]
Thanks for your effort. I will test as soon as you upload.

**Comment by juank-pa** [comment]
I uploaded a new version of the ANE to PR #14, please download it from that branch and use it. Please keep me posted on your issues. Remember to always use the ANE at `bin/dist` folder.

**Comment by subdan** [comment]
I've successfully packaged my app with this version of ANE.

**Comment by dr-mms** [comment]
Thanks successfully packaged and it works.

**Comment by juank-pa** [comment]
You are welcome to try version 1.2.0. Is a lot lighter than previous versions and added more features like background button actions and text field actions. I removed the dependency on some Android libraries to make it lighter and to prevent collisions with other ANEs.
