### ISSUE TITLE
Unable to make ANE for Android

### ISSUE THREAD

**Issue by Sumeet-basak** [juank-pa/JKLocalNotifications-ANE#38]
Hi,

When i try to make ANE build using the shell scripts available in the bin folder, it tells me that build.xml file is missing.

When I try to make the Jar file for Android, I am unable to do so. I am no expert with Android or AndroidStudio. Here is the error:
```
Error:FAILURE: Build failed with an exception.

* What went wrong:
Task 'assemble' not found in root project 'AndroidStudio'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

I had made the iOS version and it works perfectly, however when i try to make an APK with a pre-built ANE that supports iOS and Android then it gives me this error:
```
aapt tool failed:/private/var/folders/yf/dxfy5sgd5059v7ztd_t1094w0000gn/T/f6c62ea5-9f51-4d6d-8a47-0a4fcb3772b3/com.facebook-res/values/values.xml:131: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.NoActionBar'.

/private/var/folders/yf/dxfy5sgd5059v7ztd_t1094w0000gn/T/f6c62ea5-9f51-4d6d-8a47-0a4fcb3772b3/com.facebook-res/values/values.xml:136: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Dialog'.
```

I am trying to remove dependencies from AppCompatv7 and supportv4 but fail to make android builds :(

Your help is appreciated.

**Comment by juank-pa** [comment]
Sorry for the late response. Just let me analyze your case and I'll reach you as soon as I find an answer.

**Comment by Sumeet-basak** [comment]
Thanks for getting back.

I have found a work around to the problem.

I did made changes to the gradle build config to keep the support JAR files as "Provided" so that they are not added to the AAR file that is needed for the ANE.

Apart from that, i modified options_android to not have the dependancies and then it worked for me.


I will write a detailed report or if you want, i could contribute to a branch.

________________________________

**Comment by juank-pa** [comment]
Yes, I was looking at the issue and found the same things. The ANE works if its the only ANE in the project or if used along other ANES that do not include the AppCompat and Supportv4 libraries. Once another ANE includes this libraries collisions prevent the APK from building.

I would be great if you can help me fix this issue. This is something I've had in mind for some time. What we need is to do the same thing you are suggesting while providing the AppCompat and Supportv4 libraries as external ANES for the people to download. That way they can decide whether they need to add it or not.

I had some issues recently too with the compile option but instead of using `provided` which is considered deprecated I used `compileOnly` in these WIP branch #39.

Feel free to fork the project change it as you desire and make a PR to work on it together. Thanks in advance.

**Comment by juank-pa** [comment]
`

**Comment by juank-pa** [comment]
BTW don't use PR #39 as a base it is a WIP and is not yet finished. Branch it from master.

**Comment by Sumeet-basak** [comment]
Understood. Will contribute once i get this project out of the way.

Thank you, its a useful tool you put together.

________________________________

**Comment by juank-pa** [comment]
Hey @Sumeet-basak good news. At the beginning your idea of getting rid of dependencies into external files was great. But I ended up doing something even better. I noticed I was depending on these libraries for very few things. So I removed the dependency completely and handled the SDK dependencies myself. You can see changes in PR #40. Tell me what you think.

**Comment by juank-pa** [comment]
@Sumeet-basak I invite you to try the latest build.

**Comment by Sumeet-basak** [comment]
Thanks for the invite. i am testing it now.
