### ISSUE TITLE
New apps must target at least Android 9.0 (API level 28)

### ISSUE THREAD

**Issue by kanghoon75** [juank-pa/JKLocalNotifications-ANE#54]
I am using your JKLocalNotifications-ANE and thank you for your hard work. 
Google's recent policy revisions have made it difficult to use your ane. 
I would like to know if there is a support plan for Android api. 
Thank you.

-------------------------------------------------------------------------------------------
https://developer.android.com/distribute/best-practices/develop/target-sdk

When you upload an APK, it needs to meet Google Play’s target API level requirements:

New apps must target at least Android 9.0 (API level 28)
From November 1, 2019, app updates must target at least Android 9.0. Until this date, app updates must target at least Android 8.0 (API level 26)

**Comment by juank-pa** [comment]
Sorry for taking it that long. For some reason Github has not being sending me emails anymore.
And  because I stopped looking at this repo actively  I just missed the issue.
Even if fixing this should be simple due to the source code being shipped with the repo I'll try to generate a new version with the new targets in the next weeks.

**Comment by juank-pa** [comment]
@kanghoon75 I have an answer for you, the ANE is not tied to a specific Android SDK, it can still work with the latest ones, instead what must change is the supported Android version of Adobe AIR.
Adobe AIR 29 started supporting API level 27 (8.1). But Adobe hasn't release anything yet to support any Android higher version. When this becomes available from Adobe then you'll also need to update the target android version in your App Manifest XML file.

In the meantime. Not having AIR use the latest Android SDK should not stop you, you can download your own version of the Android SDK and you can modify the command line to point to the Android SDK you downloaded.

If you use Adobe Animate or any other GUI, there might be a way to specify a custom SDK somewhere. I'm not used to using this GUI software, so I can't help you that much with that, sorry.

**Comment by kanghoon75** [comment]
Thank you for your reply. 
Your "ane" doesn't support "notification channels". 
So does not work on devices above Android 8.0. 
If you targetting to Android SDK 26 or low at App Manifest XML file, the alarm will be running. 
But you can not upload in the PlayStore anymore.
Thank you.

**Comment by kanghoon75** [comment]
Your "ane" still works well in ios. 
I think your "ane" is better than the others. 
If you plan to keep updating in the future, please let me know.
Thanks and best regards.

**Comment by juank-pa** [comment]
@kanghoon75 now that you mention it, yeah you're right about the notifications channel, which reminds me I left a PR in progress to support them. I might resume that work later this month. I'm traveling this following weeks so I can't do it right away.

**Comment by juank-pa** [comment]
@kanghoon75 I managed to make a beta build before my trip, you can try testing it during the week if you want https://github.com/juank-pa/JKLocalNotifications-ANE/releases/tag/v1.5.0-beta.

Basically the `NotificationCategory` class represents the Android channels. If you've never used them in your code before, a default category (Android channel) will be created. I you want to customize this default channel you can use `NotificationManager.setupDefaultCategory`. This default category affects only Android and cannot have action buttons.

If you want a similar experience between iOS and Android when it comes to action buttons just create custom channels.

The only breaking change is that you need to attend to `NotificationCategory.name` if you've used categories before, because the name is required in Android.

You also need to define sound, importance, etc twice: in `NotificationCategory`and `Notification` if you also want to support legacy Android versions or iOS.

All that is explained in the docs and you can also refer to `Sample.as`.

**Comment by kanghoon75** [comment]
Thank you for your work. It works perfectly on Android 8.0 and above.
Sorry for the late reply. When I first tested this "ane" last month, I thought it was buggy. 
Just yesterday, I realized that I didn't delete the test code that I put in for other tasks. 
All the bugs were caused by my test code. 
Thank you.
I’m always rooting for you.
